### ISSUE TITLE
show units without gps position

### ISSUE THREAD

**Issue by fs1** [wrk-fmd/geoclient#17]
Units which have no (permanent) GPS position, are not shown on the map, even if the position was set via CoCeSo. Please adapt geoclient to also view this units (maybe with a new color code).

**Comment by heinrichmartin** [comment]
Consider the architecture CoCeSo/geobroker/geoclient. Geoclient displays **only [units](https://github.com/wrk-fmd/geobroker/blob/fbd4f873b80437406a3d0aa1a876dac039584483/geobroker/src/main/resources/static/api/v1/coceso_geobroker.yaml#L314-L336) with a `currentPosition`**. It will then draw lines on mouse over - one for `lastPoint` and one for `targetPoint` (both are optional).

Shouldn't this be implemented in CoCeSo? I.e. set the `currentPosition`.

Otherwise, how to identify the units you are missing?

**Comment by heinrichmartin** [comment]
Having thought about it a bit, do you want to show units that have a `lastPoint`, but not a `currentPosition`?

Suggested implementation: track whether a unit is "online". Units that are not online, will be shown in gray.

Online units have a `currentPosition` that is not older than 30 minutes.
Offline units are displayed at their (outdated) `currentPosition` if available or at their `lastPoint`. Internally, the `currentPosition` will be overwritten, but the online status is tracked.
Units that have neither `currentPosition` nor `lastPoint` will still not be shown.

@fs1 , @robo-w , is this the accepted solution?

**Comment by heinrichmartin** [comment]
Feedback by email confirmed most of the last comment.

Offline units are now gray; the circle color is reserved for #4.
Note that `lastPosition` is displayed in opaque gray, while outdated `currentPosition` is faded gray.
The online timeout is configurable in milliseconds as `onlineTimeout` (default is 30 * 60 * 1000).
